"""add_batch_id_to_analysis_history

Revision ID: 3ed2a68208e3
Revises: 04be3a0ce808
Create Date: 2025-12-08 17:07:44.221166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ed2a68208e3'
down_revision: Union[str, Sequence[str], None] = '04be3a0ce808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_history', sa.Column('batch_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_analysis_history_batch_id'), 'analysis_history', ['batch_id'], unique=False)
    op.drop_constraint(op.f('analysis_history_user_id_fkey'), 'analysis_history', type_='foreignkey')
    op.create_foreign_key(None, 'analysis_history', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('idx_document_chunks_embedding_vector'), table_name='document_chunks', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('ix_document_chunks_user_id'), table_name='document_chunks')
    op.create_index('idx_document_chunks_filename', 'document_chunks', ['source_filename'], unique=False)
    op.create_index('idx_document_chunks_user_id', 'document_chunks', ['user_id'], unique=False)
    op.drop_constraint(op.f('document_chunks_user_id_fkey'), 'document_chunks', type_='foreignkey')
    op.create_foreign_key(None, 'document_chunks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.create_foreign_key(op.f('document_chunks_user_id_fkey'), 'document_chunks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_document_chunks_user_id', table_name='document_chunks')
    op.drop_index('idx_document_chunks_filename', table_name='document_chunks')
    op.create_index(op.f('ix_document_chunks_user_id'), 'document_chunks', ['user_id'], unique=False)
    op.create_index(op.f('idx_document_chunks_embedding_vector'), 'document_chunks', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_constraint(None, 'analysis_history', type_='foreignkey')
    op.create_foreign_key(op.f('analysis_history_user_id_fkey'), 'analysis_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_analysis_history_batch_id'), table_name='analysis_history')
    op.drop_column('analysis_history', 'batch_id')
    # ### end Alembic commands ###
