"""initial tables - user and analysis history

Revision ID: 76727aca3dc8
Revises: 
Create Date: 2025-11-24 19:32:32.372583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76727aca3dc8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rfp_filename', sa.String(length=500), nullable=False),
    sa.Column('num_provided_docs', sa.Integer(), nullable=False),
    sa.Column('num_required_docs', sa.Integer(), nullable=False),
    sa.Column('num_matched', sa.Integer(), nullable=False),
    sa.Column('num_review', sa.Integer(), nullable=True),
    sa.Column('num_missing', sa.Integer(), nullable=False),
    sa.Column('completion_rate', sa.Float(), nullable=False),
    sa.Column('api_cost', sa.Float(), nullable=True),
    sa.Column('results_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_history_id'), 'analysis_history', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_history_user_id'), 'analysis_history', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_analysis_history_user_id'), table_name='analysis_history')
    op.drop_index(op.f('ix_analysis_history_id'), table_name='analysis_history')
    op.drop_table('analysis_history')
    # ### end Alembic commands ###
